# Generated by Django 5.2.17 on 2026-09-27 15:15

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('lang', models.CharField(choices=[('fa', 'Fa'), ('ar', 'Ar'), ('en', 'En')], default='fa', max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=10)),
                ('elo', models.IntegerField(default=1500)),
                ('xp', models.BigIntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('age_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='user_username_ci_unique')],
            },
        ),
    ]
