# Generated by Django 5.2.17 on 2026-09-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('fa', 'Fa'), ('en', 'En')], default='fa', max_length=2),
        ),
    ]
