# Generated by Django 5.2.17 on 2026-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phone_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="equipped",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="username_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
