# Generated by Django 5.2.17 on 2026-09-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralearning",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("held", "Held"),
                    ("cancelled", "Cancelled"),
                ],
                default="paid",
                max_length=10,
            ),
        ),
    ]
