# Generated by Django 5.2.17 on 2026-09-28 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_otp_session_profile'),
        ('adminapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=26)),
                ('bank_code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_account',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tx_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('account', models.CharField(max_length=64)),
                ('amount', models.BigIntegerField()),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('match_entry', 'Match Entry'), ('match_payout', 'Match Payout'), ('match_refund', 'Match Refund'), ('rake', 'Rake'), ('referral_commission', 'Referral Commission'), ('prediction_stake', 'Prediction Stake'), ('prediction_payout', 'Prediction Payout'), ('prediction_refund', 'Prediction Refund'), ('tournament_entry', 'Tournament Entry'), ('tournament_prize', 'Tournament Prize'), ('tournament_refund', 'Tournament Refund'), ('signup_bonus', 'Signup Bonus'), ('level_reward', 'Level Reward'), ('achievement_reward', 'Achievement Reward'), ('shop_purchase', 'Shop Purchase'), ('username_change', 'Username Change'), ('admin_adjustment', 'Admin Adjustment'), ('admin_topup', 'Admin Topup'), ('withdrawal_hold', 'Withdrawal Hold'), ('withdrawal_payout', 'Withdrawal Payout'), ('withdrawal_refund', 'Withdrawal Refund'), ('transfer', 'Transfer')], max_length=32)),
                ('ref_type', models.CharField(blank=True, default='', max_length=32)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ledger_entry',
                'indexes': [models.Index(fields=['account', 'created_at'], name='ledger_entr_account_8322b4_idx'), models.Index(fields=['idempotency_key'], name='ledger_entr_idempot_453e59_idx'), models.Index(fields=['type', 'created_at'], name='ledger_entr_type_f2cf22_idx')],
                'constraints': [models.UniqueConstraint(fields=('idempotency_key', 'account'), name='ledger_idem_account_unique'), models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ledger_amount_non_zero')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.BigIntegerField(default=0)),
                ('locked', models.BigIntegerField(default=0)),
                ('version', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'wallet',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'), models.CheckConstraint(condition=models.Q(('locked__gte', 0)), name='wallet_locked_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.BigIntegerField()),
                ('fee_coins', models.BigIntegerField(default=0)),
                ('price_toman', models.BigIntegerField()),
                ('payout_rial', models.BigIntegerField()),
                ('iban', models.CharField(max_length=26)),
                ('bank_code', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('expected_by', models.DateField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('bank_reference', models.CharField(blank=True, default='', max_length=64)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_decisions', to='adminapi.adminuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawal_request',
                'indexes': [models.Index(fields=['user', 'created_at'], name='withdrawal__user_id_7dd430_idx'), models.Index(fields=['status', 'created_at'], name='withdrawal__status_37b82e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='withdrawal_idem_unique'), models.CheckConstraint(condition=models.Q(('coins__gt', 0)), name='withdrawal_coins_positive')],
            },
        ),
    ]
