# Generated by Django 5.2.17 on 2026-09-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapi", "0001_initial"),
        ("wallet", "0002_ledger_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawal_claims",
                to="adminapi.adminuser",
            ),
        ),
    ]
