# Generated by Django 5.2.17 on 2026-09-27 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('support', 'Support'), ('finance', 'Finance'), ('superadmin', 'Superadmin')], max_length=20)),
                ('totp_secret_encrypted', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='adminapi.adminuser')),
            ],
            options={
                'db_table': 'admin_session',
            },
        ),
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=100)),
                ('before', models.JSONField(null=True)),
                ('after', models.JSONField(null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='adminapi.adminuser')),
            ],
            options={
                'db_table': 'admin_audit',
                'indexes': [models.Index(fields=['admin', 'created_at'], name='admin_audit_admin_i_fbaf0e_idx'), models.Index(fields=['target_type', 'target_id'], name='admin_audit_target__ca511c_idx')],
            },
        ),
    ]
