# Generated by Django 5.2.17 on 2026-09-28 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("text_i18n", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "phrase",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("board_theme", "Board Theme"),
                            ("checker_theme", "Checker Theme"),
                            ("avatar", "Avatar"),
                            ("emoji_pack", "Emoji Pack"),
                            ("phrase_pack", "Phrase Pack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("name_i18n", models.JSONField(default=dict)),
                (
                    "unlock",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("level_locked", "Level Locked"),
                            ("purchasable", "Purchasable"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("price_coins", models.BigIntegerField(default=0)),
                ("unlock_level", models.PositiveSmallIntegerField(default=1)),
                ("data", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
                ("sort", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "item",
                "ordering": ["kind", "sort", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key"), name="item_kind_key_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("prize", "Prize"),
                            ("grant", "Grant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owners",
                        to="shop.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_item",
                "indexes": [
                    models.Index(
                        fields=["user", "acquired_at"],
                        name="user_item_user_id_51b8a8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"), name="user_item_once"
                    )
                ],
            },
        ),
    ]
