# Generated by Django 5.2.17 on 2026-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_seed_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("announcement", "Announcement"),
                        ],
                        default="announcement",
                        max_length=20,
                    ),
                ),
                ("title_i18n", models.JSONField(default=dict)),
                ("body_i18n", models.JSONField(default=dict)),
                ("link", models.CharField(blank=True, default="", max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("sort", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "announcement",
                "ordering": ["sort", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TextOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=160, unique=True)),
                ("text_i18n", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "text_override",
            },
        ),
    ]
