# Generated by Django 5.2.17 on 2026-09-28 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0003_remove_match_tier_replayview_delete_tabletier_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_i18n", models.JSONField(default=dict)),
                ("variant", models.CharField(max_length=20)),
                ("length", models.PositiveSmallIntegerField()),
                ("entry", models.BigIntegerField()),
                ("capacity", models.PositiveSmallIntegerField()),
                ("starts_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                ("prize_split", models.JSONField(default=list)),
                ("rake_pct", models.PositiveSmallIntegerField()),
                ("prize_items", models.JSONField(blank=True, default=list)),
                ("round", models.PositiveSmallIntegerField(default=0)),
                ("created_by", models.BigIntegerField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tournament",
                "indexes": [
                    models.Index(
                        fields=["status", "starts_at"],
                        name="tournament_status_ca7d32_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BracketSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.PositiveSmallIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slot",
                        to="game.match",
                    ),
                ),
                (
                    "player_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_slot",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "round", "position"), name="slot_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TournamentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "eliminated_round",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("place", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("prize", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournament_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tournament_entry",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="tournament__user_id_a3d4fd_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "user"), name="tournament_entry_once"
                    )
                ],
            },
        ),
    ]
