// GENERATED by `python manage.py protocol_ts` from backend/realtime/protocol.py. Do not edit.
// WebSocket payloads (CLAUDE.md §10.3). A backend test fails when this file is out of date.

export interface AuthIn {
  token: string;
}

export interface AuthOkOut {
  username: string | null;
}

export interface Clock {
  actor: number | null;
  deadline: number | null;
  bank: number[];
  turn_seconds: number;
  server_now: number;
}

export interface CubeUpdateOut {
  action: "offer" | "take" | "drop";
  player: number;
  value: number;
  owner: number | null;
  clock: Clock;
}

export type EmptyIn = Record<string, never>;

export interface ErrorOut {
  code: string;
  message_key: string;
  details: Record<string, unknown>;
}

export interface GameEndedOut extends GameResultOut {
  score: number[];
}

export interface GameResultOut {
  game_no: number;
  winner: number;
  kind: "single" | "gammon" | "backgammon";
  cube: number;
  points: number;
  reason: "bear_off" | "drop" | "resign";
}

export interface GameStartedOut {
  game_no: number;
  crawford: boolean;
  score: number[];
  position: string;
}

export interface HistoryEntryOut {
  player: number;
  dice: number[];
  moves: number[][];
  cube: "offer" | "take" | "drop" | null;
}

export interface MatchEndedOut {
  winner: number | null;
  score: number[];
  reason: string;
  seed: string;
  elo: Record<string, number> | null;
  xp: Record<string, number> | null;
  settlement: Record<string, number> | null;
}

export interface MatchFoundOut {
  match_id: string;
  you: number;
  opponent: PlayerInfo;
  seed_commit: string;
  variant: string;
  length: number;
  entry: number;
  join_deadline: number;
  tournament: TournamentContextOut | null;
}

export interface MatchResignIn {
  scope: "game" | "match";
}

export interface MatchRulesOut {
  turn_seconds: number;
  timebank_seconds: number;
  max_consecutive_timeouts: number;
  reconnect_grace_seconds: number;
  points: Record<string, number>;
  rake_pct: number;
  payout: number;
}

export interface MatchStateOut {
  match_id: string;
  status: "active" | "finished" | "aborted" | "voided";
  you: number | null;
  players: PlayerInfo[];
  variant: string;
  length: number;
  entry: number;
  seed_commit: string;
  score: number[];
  game_no: number;
  crawford_game: boolean;
  phase: "opening" | "roll" | "move" | "cube_offered" | "game_over" | "match_over";
  position: string;
  turn: number | null;
  dice: number[] | null;
  cube_value: number;
  cube_owner: number | null;
  can_double: boolean;
  legal: number[][][];
  clock: Clock;
  timeouts: number[];
  results: GameResultOut[];
  winner: number | null;
  end_reason: string | null;
  spectators: number;
  rules: MatchRulesOut;
  grace: (number | null)[];
  history: HistoryEntryOut[];
}

export interface MatchSyncIn {
  last_seq?: number;
}

export interface OpponentBackOut {
  player: number;
}

export interface OpponentDisconnectedOut {
  player: number;
  grace_seconds: number;
}

export interface PlayerInfo {
  username: string;
  avatar: string;
  elo: number;
  level: number;
  is_bot: boolean;
  bot_level: string | null;
  board_theme: string;
  checker_theme: string;
  connected: boolean;
}

export interface PoolUpdateOut {
  total_a: number;
  total_b: number;
  open: boolean;
}

export interface QueueJoinIn {
  tier_id: number;
  variant: "standard_cube" | "standard_nocube" | "traditional";
  length: number;
}

export interface QueueStatusOut {
  state: "waiting" | "left" | "removed";
  tier_id: number;
  variant: string;
  length: number;
  reason: string | null;
}

export interface ReactRecvOut {
  key: string;
  kind: "emoji" | "phrase";
  sender: number;
}

export interface ReactSendIn {
  emoji_key?: string | null;
  phrase_key?: string | null;
}

export interface SpectateReactIn {
  emoji_key: string;
}

export interface SpectateReactRecvOut {
  key: string;
}

export interface SpectatorsCountOut {
  count: number;
}

export interface TournamentContextOut {
  id: number;
  name: Record<string, string>;
  round: number;
  rounds: number;
}

export interface TurnMoveIn {
  moves: number[][];
}

export interface TurnMovedOut {
  player: number;
  moves: number[][];
  hits: boolean[];
  position: string;
  auto: "forced" | "timeout" | null;
  clock: Clock;
}

export interface TurnPassedOut {
  player: number;
  clock: Clock;
}

export interface TurnRolledOut {
  player: number | null;
  opening: boolean;
  dice: number[];
  throw_seed: number;
  legal: number[][][];
  clock: Clock;
}

export interface TurnTimeoutOut {
  player: number;
  count: number;
  limit: number;
}

export interface ClientMessages {
  "auth": AuthIn;
  "queue.join": QueueJoinIn;
  "queue.leave": EmptyIn;
  "match.sync": MatchSyncIn;
  "turn.roll": EmptyIn;
  "turn.move": TurnMoveIn;
  "cube.offer": EmptyIn;
  "cube.take": EmptyIn;
  "cube.drop": EmptyIn;
  "react.send": ReactSendIn;
  "match.resign": MatchResignIn;
  "spectate.join": EmptyIn;
  "spectate.leave": EmptyIn;
  "spectate.react": SpectateReactIn;
}

export interface ServerMessages {
  "auth.ok": AuthOkOut;
  "error": ErrorOut;
  "match.found": MatchFoundOut;
  "queue.status": QueueStatusOut;
  "match.state": MatchStateOut;
  "turn.rolled": TurnRolledOut;
  "turn.moved": TurnMovedOut;
  "turn.passed": TurnPassedOut;
  "turn.timeout": TurnTimeoutOut;
  "cube.update": CubeUpdateOut;
  "game.started": GameStartedOut;
  "game.ended": GameEndedOut;
  "react.recv": ReactRecvOut;
  "opponent.disconnected": OpponentDisconnectedOut;
  "opponent.back": OpponentBackOut;
  "match.ended": MatchEndedOut;
  "pool.update": PoolUpdateOut;
  "spectate.state": MatchStateOut;
  "spectators.count": SpectatorsCountOut;
  "spectate.react": SpectateReactRecvOut;
}

export type ClientMessageType = keyof ClientMessages;
export type ServerMessageType = keyof ServerMessages;

/** A server message, discriminated by `type`. */
export type ServerEnvelope = {
  [K in ServerMessageType]: {
    type: K;
    match_id: string | null;
    seq: number;
    payload: ServerMessages[K];
  };
}[ServerMessageType];

/** A client message; `seq` is the last server seq the client applied. */
export type ClientEnvelope<K extends ClientMessageType = ClientMessageType> = {
  type: K;
  match_id?: string | null;
  seq: number;
  payload: ClientMessages[K];
};
