# Generated by Django 5.2.17 on 2026-09-28 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TableTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry", models.BigIntegerField()),
                ("variants", models.JSONField(default=list)),
                ("lengths", models.JSONField(default=list)),
                ("name_i18n", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
                ("sort", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "table_tier",
                "ordering": ["sort", "entry"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("standard_cube", "Standard Cube"),
                            ("standard_nocube", "Standard Nocube"),
                            ("traditional", "Traditional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("length", models.PositiveSmallIntegerField()),
                ("entry", models.BigIntegerField(default=0)),
                ("is_bot", models.BooleanField(default=False)),
                ("bot_level", models.CharField(blank=True, default="", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("aborted", "Aborted"),
                            ("voided", "Voided"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("winner_side", models.SmallIntegerField(blank=True, null=True)),
                ("score_a", models.PositiveSmallIntegerField(default=0)),
                ("score_b", models.PositiveSmallIntegerField(default=0)),
                ("end_reason", models.CharField(blank=True, default="", max_length=40)),
                ("seed_commit", models.CharField(max_length=64)),
                ("seed_encrypted", models.TextField()),
                ("rules", models.JSONField(default=dict)),
                (
                    "tournament_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True, default="")),
                (
                    "player_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.tabletier",
                    ),
                ),
            ],
            options={
                "db_table": "match",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("winner_side", models.SmallIntegerField(blank=True, null=True)),
                ("kind", models.CharField(blank=True, default="", max_length=12)),
                ("cube", models.PositiveSmallIntegerField(default=1)),
                ("points", models.PositiveSmallIntegerField(default=0)),
                ("reason", models.CharField(blank=True, default="", max_length=12)),
                ("crawford", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="game.match",
                    ),
                ),
            ],
            options={
                "db_table": "game",
            },
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("seq", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=32)),
                (
                    "actor",
                    models.CharField(
                        choices=[
                            ("player_a", "Player A"),
                            ("player_b", "Player B"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("server_ts", models.DateTimeField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="game.match",
                    ),
                ),
            ],
            options={
                "db_table": "match_event",
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("player", models.SmallIntegerField()),
                ("dice", models.JSONField(default=list)),
                ("moves_json", models.JSONField(default=list)),
                ("cube_action", models.CharField(blank=True, default="", max_length=8)),
                (
                    "position_after",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("ts", models.DateTimeField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "db_table": "move",
            },
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("match", "number"), name="game_match_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchevent",
            constraint=models.UniqueConstraint(
                fields=("match", "seq"), name="match_event_seq_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="move",
            index=models.Index(fields=["game", "seq"], name="move_game_id_8ebf07_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["player_a", "created_at"], name="match_player__5d5b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["player_b", "created_at"], name="match_player__0bf39c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["status", "created_at"], name="match_status_93c02f_idx"
            ),
        ),
    ]
