# Generated by Django 5.2.17 on 2026-09-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_match_event_append_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="tier",
        ),
        migrations.CreateModel(
            name="ReplayView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewer_id", models.BigIntegerField()),
                (
                    "viewer_role",
                    models.CharField(
                        choices=[("player", "Player"), ("admin", "Admin")],
                        max_length=10,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replay_views",
                        to="game.match",
                    ),
                ),
            ],
            options={
                "db_table": "replay_view",
            },
        ),
        migrations.DeleteModel(
            name="TableTier",
        ),
        migrations.AddIndex(
            model_name="replayview",
            index=models.Index(
                fields=["match", "viewed_at"], name="replay_view_match_i_330766_idx"
            ),
        ),
    ]
