# Generated by Django 5.2.17 on 2026-09-28 10:17

from django.db import migrations, models

# §20.1 retention: the purge job may delete match_event rows, and only after it sets the
# transaction-local flag bg.replay_purge; every other UPDATE or DELETE is still rejected.
ALLOW_PURGE = """
CREATE OR REPLACE FUNCTION match_event_immutable() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('bg.replay_purge', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'match_event is append-only';
END
$$ LANGUAGE plpgsql;
"""

APPEND_ONLY = """
CREATE OR REPLACE FUNCTION match_event_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'match_event is append-only';
END
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_match_tier_replayview_delete_tabletier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="replay_purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(ALLOW_PURGE, APPEND_ONLY),
    ]
