# Generated by Django 5.2.17 on 2026-09-28 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins", models.BigIntegerField()),
                ("name_i18n", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
                ("sort", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "coin_package",
                "ordering": ["sort", "coins"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("coins", models.BigIntegerField()),
                ("price_toman", models.BigIntegerField()),
                ("amount_rial", models.BigIntegerField()),
                ("gateway", models.CharField(max_length=20)),
                (
                    "authority",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                ("card_mask", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("callback_received", "Callback Received"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("surface", models.CharField(default="m", max_length=8)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("failure", models.CharField(blank=True, default="", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.coinpackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="payment_user_id_50b433_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="payment_status_271abe_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "idempotency_key"), name="payment_idem_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("coins__gt", 0)),
                        name="payment_coins_positive",
                    ),
                ],
            },
        ),
    ]
