# Generated by Django 5.2.17 on 2026-09-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_seed_packages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("gateway", models.CharField(max_length=20)),
                ("verified_count", models.PositiveIntegerField(default=0)),
                ("verified_rial", models.BigIntegerField(default=0)),
                ("problems", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_reconciliation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "gateway"), name="reconcile_once_per_day"
                    )
                ],
            },
        ),
    ]
