"""Generates packages/protocol/src/ws.ts from the pydantic protocol models (CLAUDE.md §10.3 contract)."""

import types
import typing
from pathlib import Path
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel

from realtime import protocol

TS_PATH = Path(__file__).resolve().parents[2] / "packages" / "protocol" / "src" / "ws.ts"
HEADER = """// GENERATED by `python manage.py protocol_ts` from backend/realtime/protocol.py. Do not edit.
// WebSocket payloads (CLAUDE.md §10.3). A backend test fails when this file is out of date.
"""


def _ts(annotation: Any, models: dict[str, type[BaseModel]]) -> str:
    origin = get_origin(annotation)
    if annotation is str:
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is type(None):
        return "null"
    if annotation is Any:
        return "unknown"
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        models[annotation.__name__] = annotation
        return annotation.__name__
    if origin is Literal:
        return " | ".join(f'"{v}"' if isinstance(v, str) else str(v).lower() for v in get_args(annotation))
    if origin in (typing.Union, types.UnionType):
        return " | ".join(_ts(a, models) for a in get_args(annotation))
    if origin is list:
        inner = _ts(get_args(annotation)[0], models)
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if origin is dict:
        return f"Record<string, {_ts(get_args(annotation)[1], models)}>"
    raise TypeError(f"no TypeScript mapping for {annotation!r}")


def _interface(model: type[BaseModel], models: dict[str, type[BaseModel]]) -> str:
    bases = [
        b
        for b in model.__bases__
        if issubclass(b, BaseModel) and b is not protocol._Model and b is not BaseModel
    ]
    own = set(model.model_fields) - {f for b in bases for f in b.model_fields}
    lines = []
    for name, info in model.model_fields.items():
        if name not in own:
            continue
        optional = "?" if model.__name__.endswith("In") and not info.is_required() else ""
        lines.append(f"  {name}{optional}: {_ts(info.annotation, models)};")
    for b in bases:
        models[b.__name__] = b
    extends = f" extends {', '.join(b.__name__ for b in bases)}" if bases else ""
    body = "\n".join(lines)
    return (
        f"export interface {model.__name__}{extends} {{\n{body}\n}}"
        if lines
        else f"export type {model.__name__} = Record<string, never>;"
    )


def generate() -> str:
    models: dict[str, type[BaseModel]] = {}
    for m in [*protocol.CLIENT_MESSAGES.values(), *protocol.SERVER_MESSAGES.values()]:
        models[m.__name__] = m
    out: dict[str, str] = {}
    while len(out) < len(models):
        for name, model in sorted(models.items()):
            if name not in out:
                out[name] = _interface(model, models)
    parts = [HEADER.rstrip()]
    parts += [out[name] for name in sorted(out)]
    client = "\n".join(f'  "{k}": {v.__name__};' for k, v in protocol.CLIENT_MESSAGES.items())
    server = "\n".join(f'  "{k}": {v.__name__};' for k, v in protocol.SERVER_MESSAGES.items())
    parts.append(f"export interface ClientMessages {{\n{client}\n}}")
    parts.append(f"export interface ServerMessages {{\n{server}\n}}")
    parts.append(
        "export type ClientMessageType = keyof ClientMessages;\n"
        "export type ServerMessageType = keyof ServerMessages;\n\n"
        "/** A server message, discriminated by `type`. */\n"
        "export type ServerEnvelope = {\n"
        "  [K in ServerMessageType]: {\n"
        "    type: K;\n    match_id: string | null;\n    seq: number;\n"
        "    payload: ServerMessages[K];\n  };\n"
        "}[ServerMessageType];\n\n"
        "/** A client message; `seq` is the last server seq the client applied. */\n"
        "export type ClientEnvelope<K extends ClientMessageType = ClientMessageType> = {\n"
        "  type: K;\n  match_id?: string | null;\n  seq: number;\n  payload: ClientMessages[K];\n};"
    )
    return "\n\n".join(parts) + "\n"
